# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

variables:
  IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  IMAGE_CACHE_REGISTRY: $CI_REGISTRY_IMAGE/cache
  PYTEST_COV_MODULE: mo_delay_agent

stages:
  - lint
  - test
  - coverage
  - build
  - release


include:
  - project: 'labs/salt-automation'
    ref: 'master'
    file: '/gitlab-ci-templates/common/autopub.v1.yml'
  - project: 'labs/salt-automation'
    ref: 'master'
    file: '/gitlab-ci-templates/common/docker-build.v1.yml'
  - project: labs/salt-automation
    ref: master
    file: gitlab-ci-templates/python/pytest.v1.yml

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

Pre-commit:
  stage: lint
  interruptible: true
  needs: []
  image: python:3.9
  before_script:
    - pip install --no-cache-dir poetry
    - poetry install
  script:
    - poetry run pre-commit run --all-files
