# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

stages:
  - lint
  - test
  - build
  - release


include:
  - project: 'labs/salt-automation'
    ref: 'master'
    file: '/gitlab-ci-templates/common/autopub.v1.yml'
  - project: 'labs/salt-automation'
    ref: 'master'
    file: '/gitlab-ci-templates/common/docker-build-meta.v1.yml'
  - project: labs/salt-automation
    ref: master
    file: gitlab-ci-templates/python/pytest-meta.v1.yml

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

Pre-commit:
  stage: lint
  interruptible: true
  needs: []
  image: python:3.8
  before_script:
    - pip install --no-cache-dir poetry
    - poetry install
  script:
    - poetry run pre-commit run --all-files

Unit-test:
  extends: .pytest

Build:
  needs: ["Unit-test"]
  extends: .build-docker