version: "3"

services:
    delay-db:
        image: "postgres:9.6"
        ports:
            - 5432:5432
        env_file:
            - pg.env
        volumes:
            - "./delay.sql:/docker-entrypoint-initdb.d/delay.sql"
