version: "3"

services:
    delay-agent:
        build: .
        env_file:
            - pg.env
            - amqp.env
        environment:
            amqp_url: amqp://guest:guest@amqp:5672
            postgresurl: postgres://delay_agent:delay_agent@delay-db:5432/delay_agent
        depends_on:
            - delay-db
            - amqp

    delay-db:
        image: "postgres:9.6"
        env_file:
            - pg.env
        volumes:
            - "./delay.sql:/docker-entrypoint-initdb.d/delay.sql"

    amqp:
        image: rabbitmq:3.5
        env_file:
            - amqp.env
