version: "3"

services:
    db:
        image: "postgres:9.6"
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=delay_agent
            - POSTGRES_USER=delay_agent
            - POSTGRES_PASSWORD=delay_agent
        volumes:
            - "./delay.sql:/docker-entrypoint-initdb.d/delay.sql"
    test_order_db:
        build: ./PostgresFakeTimeDocker/
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_DB=delay_agent
            - POSTGRES_USER=delay_agent
            - POSTGRES_PASSWORD=delay_agent
        volumes:
            - "./delay.sql:/docker-entrypoint-initdb.d/delay.sql"
    test_end_to_end_db:
        build: ./PostgresFakeTimeDocker/
        ports:
            - "5434:5432"
        environment:
            - POSTGRES_DB=delay_agent
            - POSTGRES_USER=delay_agent
            - POSTGRES_PASSWORD=delay_agent
        volumes:
            - "./delay.sql:/docker-entrypoint-initdb.d/delay.sql"
    amqp:
        image: rabbitmq:3.5
        ports:
            - "4369:4369"
            - "5671:5671"
            - "5672:5672"
            - "25672:25672"

