# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    rebase-strategy: auto
    auto-merge:
      squash: true

